trigger:
  branches:
    include:
      - main  # Adjust if using a different branch

pool:
  vmImage: 'ubuntu-latest'  # Use a Linux agent; Windows is also an option if preferred

variables:
  AZURE_SUBSCRIPTION: 'your-subscription-id'
  RESOURCE_GROUP: 'VideoApplicationRG'
  APP_SERVICE_NAME: 'VideoAppService'

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            displayName: 'Install Dependencies'

  - stage: Test
    dependsOn: Build
    jobs:
      - job: TestJob
        steps:
          - script: |
              # Run any tests here, e.g., pytest
              pytest
            displayName: 'Run Unit Tests'

  - stage: Deploy
    dependsOn: Test
    jobs:
      - deployment: DeployToAzure
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: $(AZURE_SUBSCRIPTION)
                    appName: $(APP_SERVICE_NAME)
                    package: $(System.DefaultWorkingDirectory)/**/*.zip
